SELECT * FROM VENTA_X_COBRAR WHERE  NRODOCU='150005814'



SELECT * FROM NARGEST.DBO.VENTACAB WHERE NRODOCU='150005814'


180008841
150005814

120008030



DROP TABLE dbo.Hoja1$



SELECT * FROM dbo.Hoja1$ WHERE DOCUMENTO IS NOT NULL

select * from NARGEST.DBO.VENTACAB WHERE NRODOCU in(SELECT right(documento,9) FROM dbo.Hoja1$ WHERE DOCUMENTO IS NOT NULL)


select * from NARGEST.DBO.VENTA_X_COBRAR WHERE NRODOCU in(SELECT right(documento,9) FROM dbo.Hoja1$ WHERE DOCUMENTO IS NOT NULL)


SELECT * FROM NARGEST.DBO.CLIENTE WHERE CODCLIENTE ='11530001'


INSERT INTO  NARGEST.DBO.VENTA_X_COBRAR(CDTIPODOCUM, NRODOCU, CDMONEDA, CDCLIENTE, TOTCREDBAS, TOTCREDEXT, FECDOCUM, PLAZO, VENCIMIENTO, ESTADO, PAGCREDBAS, PAGCREDEXT, TIPCREDFAC, TRANS, CODEMPRESA, CDCLIENTEDEP, PTOVTA, DOCUREF, fproceso, PAG, DSCLIENTE)
SELECT V.[tipo documento] AS DOC,right(V.documento,9) AS NRODOC,'S' AS MONEDA,CONVERT(INT,V.PRINCIPAL) AS CDCLIENTE,V.IMPORTE,0,V.FECHA_EMISION,0,V.FECHA_EMISION,'PENDIENTE',0,0,0,0,'01',CONVERT(INT,V.DEPEND) AS DEPEND,'CAJA04','',V.FECHA_EMISION,0,C.RAZONSOCIAL FROM dbo.Hoja1$ V  
INNER JOIN NARGEST.DBO.CLIENTE C ON C.CODCLIENTE=CONVERT(INT,V.DEPEND)
WHERE V.DOCUMENTO IS NOT NULL
AND right(documento,9)='150038193'



SELECT * FROM NARGEST.DBO.VENTA_X_COBRAR WHERE NRODOCU ='150038193'


DELETE FROM NARGEST.DBO.VENTA_X_COBRAR WHERE NRODOCU ='150038193' 


DELETE FROM NARGEST.DBO.GUIAINTERNADET WHERE NRODOCFACT ='150038193' 



INSERT INTO NARGEST.DBO.GUIAINTERNADET(CODEMPRESA,NRODOCFACT,CODTIPOPAGO,MONTODESCT2,MONTODESCT1,ESTADO,ITEM)


HHH

SELECT * FROM NARGEST.DBO.VENTACAB WHERE NRODOCU='150038193'

DELETE FROM NARGEST.DBO.VENTACAB WHERE NRODOCU='150038193'




SELECT * FROM dbo.Hoja1$ 
SELECT * FROM NARGEST.DBO.CLIENTE


INSERT INTO NARGEST.DBO.VENTACAB(CODEMPRESA, CODTIPODOC, NRODOCU, CODMON, CAMBIO, CODTIPOPAGO, CODVEND, ESTADO, FECDOCUM, FECPROCESO, CODIMPUESTO, TOTBAS, CODCLIENTE, RUCCLIENTE, DESCLIENTE, DIRCLIENTE, CIERREZ, CDUSUARIO, NROPTOVTA, FECANULA, CDTIPOANULA, CDZONA, NROGUIA, CODDEP, OBSERV, POSTPAGO,SUBTOTBAS,TOTEXT,SUBTOTEXT)
SELECT '01',V.[tipo documento] AS DOC,right(V.documento,9) AS NRODOC,'S' AS MONEDA,3.3,V.[tipo pago] AS tipopago,vendedor,'',V.FECHA_EMISION,V.FECHA_EMISION,'',V.IMPORTE,CONVERT(INT,V.PRINCIPAL) AS CDCLIENTE,C.RUC,C.RAZONSOCIAL,C.DIRECCION,0,'2411','CAJA02',V.FECHA_EMISION,0,'01',0,CONVERT(INT,V.DEPEND) AS DEPEND,'',0,0,0,0 FROM dbo.Hoja1$ V  
INNER JOIN NARGEST.DBO.CLIENTE C ON C.CODCLIENTE=CONVERT(INT,V.DEPEND)
WHERE V.DOCUMENTO IS NOT NULL
AND right(documento,9)='150038193'


HHH



ALTER  PROCEDURE HHH
AS
DECLARE @CODARTI  varchar(255) 
-- Declaración del cursor
DECLARE cClientes CURSOR FOR

SELECT right(documento,9) FROM dbo.Hoja1$ WHERE DOCUMENTO IS NOT NULL

OPEN cClientes
FETCH cClientes INTO @CODARTI
WHILE (@@FETCH_STATUS = 0 )

BEGIN
    -- Lectura de la siguiente fila del cursor

INSERT INTO NARGEST.DBO.VENTACAB(CODEMPRESA, CODTIPODOC, NRODOCU, CODMON, CAMBIO, CODTIPOPAGO, CODVEND, ESTADO, FECDOCUM, FECPROCESO, CODIMPUESTO, TOTBAS, CODCLIENTE, RUCCLIENTE, DESCLIENTE, DIRCLIENTE, CIERREZ, CDUSUARIO, NROPTOVTA, FECANULA, CDTIPOANULA, CDZONA, NROGUIA, CODDEP, OBSERV, POSTPAGO,SUBTOTBAS,TOTEXT,SUBTOTEXT)
SELECT '01',V.[tipo documento] AS DOC,right(V.documento,9) AS NRODOC,'S' AS MONEDA,3.3,V.[tipo pago] AS tipopago,vendedor,'',V.FECHA_EMISION,V.FECHA_EMISION,'',V.IMPORTE,CONVERT(INT,V.PRINCIPAL) AS CDCLIENTE,C.RUC,C.RAZONSOCIAL,C.DIRECCION,0,'2411','CAJA02',V.FECHA_EMISION,0,'01',0,CONVERT(INT,V.DEPEND) AS DEPEND,'',0,0,0,0 FROM dbo.Hoja1$ V  
INNER JOIN NARGEST.DBO.CLIENTE C ON C.CODCLIENTE=CONVERT(INT,V.DEPEND)
WHERE V.DOCUMENTO IS NOT NULL
AND right(documento,9)=@CODARTI


FETCH cClientes INTO  @CODARTI
END

-- Cierre del cursor

CLOSE cClientes

-- Liberar los recursos

DEALLOCATE cClientes




