// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Linea_ventaAnulado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Linea_ventaAnulado));
        
        string IMigrationMetadata.Id
        {
            get { return "201809180013192_Linea_ventaAnulado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
