// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregandoCODARTI_VTAenClienteXPromo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandoCODARTI_VTAenClienteXPromo));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131744183_agregando CODARTI_VTA en ClienteXPromo "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
