// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_tabla_cierre_inv_gloria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tabla_cierre_inv_gloria));
        
        string IMigrationMetadata.Id
        {
            get { return "201901282210487_create_tabla_cierre_inv_gloria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
