// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creandotablasEquipo_VendedoryJefe_Equipo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creandotablasEquipo_VendedoryJefe_Equipo));
        
        string IMigrationMetadata.Id
        {
            get { return "201907271948519_creando tablas Equipo_Vendedor y Jefe_Equipo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
