// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambie_TipoPrecioXPromoSubCatSoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambie_TipoPrecioXPromoSubCatSoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202012150433250_cambie_TipoPrecioXPromoSubCatSoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
