// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ventacabfe_envio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ventacabfe_envio));
        
        string IMigrationMetadata.Id
        {
            get { return "202005280044510_ventacabfe_envio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
