// <auto-generated />
namespace Dominio.Contextos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hdocdosnuevoscampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hdocdosnuevoscampos));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251715225_hdoc dos nuevos campos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
