//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVO
    {
        public string IDACTIVO { get; set; }
        public string ACTIVO1 { get; set; }
        public decimal IDDEPA { get; set; }
        public string CODEMPRESA { get; set; }
        public Nullable<bool> TRANS { get; set; }
        public System.DateTime DATETRANS { get; set; }
        public Nullable<decimal> HP { get; set; }
        public decimal KW { get; set; }
        public Nullable<decimal> PUKW { get; set; }
        public decimal CostHor { get; set; }
    }
}
