//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVO_FIJO
    {
        public string CODACT { get; set; }
        public string DESCACT { get; set; }
        public string CODDEP { get; set; }
        public string CODEMPRESA { get; set; }
        public Nullable<decimal> TASDEPCONT { get; set; }
        public Nullable<decimal> TASDEPTRIB { get; set; }
        public string TASDEPDOL { get; set; }
        public Nullable<decimal> VIDUTIL { get; set; }
        public Nullable<decimal> CORRELATIVO { get; set; }
    }
}
