//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALMAZON
    {
        public string CDZONA { get; set; }
        public string CDALMACEN { get; set; }
        public string USERID { get; set; }
        public byte[] TSTAMP { get; set; }
        public bool TRANS { get; set; }
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public string CODEMPRESA { get; set; }
    }
}
