//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIDAT
    {
        public string CODEMPRESA { get; set; }
        public string CODALMACEN { get; set; }
        public string CODARTI { get; set; }
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public Nullable<bool> TRANS { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<System.DateTime> ULTSAL { get; set; }
        public Nullable<System.DateTime> ULTING { get; set; }
        public Nullable<decimal> COSTEXTRM { get; set; }
        public Nullable<decimal> COSTEXTRU { get; set; }
        public Nullable<decimal> COSTBASEM { get; set; }
        public Nullable<decimal> COSTBASEU { get; set; }
        public Nullable<decimal> STKINIM { get; set; }
        public Nullable<decimal> STKINIU { get; set; }
        public Nullable<decimal> STKACTM { get; set; }
        public Nullable<decimal> STKACTU { get; set; }
        public Nullable<decimal> STKMAXM { get; set; }
        public Nullable<decimal> STKMAXU { get; set; }
        public Nullable<decimal> STKMINM { get; set; }
        public Nullable<decimal> STKMINU { get; set; }
        public string UBICAJE { get; set; }
        public string NROING { get; set; }
        public string NROSAL { get; set; }
        public Nullable<System.DateTime> FECH_COMP { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
    }
}
