//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIERRE_MES_INVENTARIO
    {
        public string AÑO { get; set; }
        public string MES { get; set; }
        public string ARTICULO { get; set; }
        public Nullable<int> STOCK { get; set; }
        public string ALMACEN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public byte[] TSTAMP { get; set; }
        public int ID { get; set; }
    }
}
