//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIDEP
    {
        public string CODEMPRESA { get; set; }
        public string CODDEP { get; set; }
        public string CODCLIENTE { get; set; }
        public bool ACTIVO { get; set; }
        public string CODRUTA { get; set; }
        public string CODDISTRITO { get; set; }
        public Nullable<decimal> MPERCEP { get; set; }
        public Nullable<bool> notapedido { get; set; }
        public Nullable<bool> ORT { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual RUTA RUTA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
