//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIE_FUERZA
    {
        public string CODEMPRESA { get; set; }
        public string CODCLIE { get; set; }
        public string CODFUERZA { get; set; }
        public Nullable<decimal> CREDITO_F { get; set; }
        public Nullable<decimal> SALDO_CREDF { get; set; }
        public int ID { get; set; }
    
        public virtual FUERZAVENTA FUERZAVENTA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
