//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGVTA
    {
        public string CODEMPRESA { get; set; }
        public bool INCLUYE_SERV { get; set; }
        public decimal PORCENSERV { get; set; }
        public string IDIMPIGV { get; set; }
        public string IDIMPISC { get; set; }
        public decimal NRORESERVA { get; set; }
        public decimal NROCONSUMO { get; set; }
        public Nullable<decimal> NRORECPEND { get; set; }
        public Nullable<decimal> NROPAGOCTACTE { get; set; }
        public Nullable<decimal> NROPAGPROV { get; set; }
        public bool EDITPRECIO { get; set; }
        public string CDTICKET { get; set; }
        public string CDFACTURA { get; set; }
        public string CDBOLETA { get; set; }
        public string CDGUIATRANSFER { get; set; }
        public string CDNTACREDP { get; set; }
        public string CDNTAPEDIDO { get; set; }
        public string CDBALANZA { get; set; }
        public string CDNTADEBITO { get; set; }
        public string CDGUIA { get; set; }
        public string CDGUIAVENTA { get; set; }
        public string CDGUIAREMISION { get; set; }
        public string CODCLIVARIOS { get; set; }
        public Nullable<decimal> IDSOCIO { get; set; }
        public bool ACT_PRE_OFER { get; set; }
        public bool ACT_PRE_ADI { get; set; }
        public bool ACT_PRE_EXT { get; set; }
        public bool DESCXCAT { get; set; }
        public bool IMPCUPONES { get; set; }
        public Nullable<byte> MONTO_CUPON { get; set; }
        public Nullable<byte> NUM_CUPON { get; set; }
        public bool ACTBONUS { get; set; }
        public byte[] TSTAMP { get; set; }
        public bool TRANS { get; set; }
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public Nullable<bool> codgenclie { get; set; }
        public Nullable<decimal> ITEMDEGUIA { get; set; }
        public Nullable<decimal> ITEMDENOTACRED { get; set; }
        public Nullable<decimal> ITEMDEBOLETA { get; set; }
        public Nullable<decimal> ITEMDEFACT { get; set; }
        public int ITEMDENTAPEDIDO { get; set; }
        public string IDNOIMPIGV { get; set; }
        public string codvend { get; set; }
        public Nullable<decimal> montoboleta { get; set; }
        public Nullable<decimal> DIGITOSRUC { get; set; }
        public Nullable<decimal> DIGITOSDNI { get; set; }
        public Nullable<decimal> UIT { get; set; }
        public Nullable<decimal> CORRELNROPAGO { get; set; }
        public Nullable<bool> DESCARGA_ALMACEN { get; set; }
        public string CODARTISERV { get; set; }
        public Nullable<int> DURACION_PEDIDO { get; set; }
        public bool NTACRED_INS_CUENTA_CLIE { get; set; }
        public Nullable<bool> CAMBFECFACT { get; set; }
        public bool PRECIO_CONIGV { get; set; }
        public string CDPAGEFECTIVO { get; set; }
        public string CDPAGCREDITO { get; set; }
        public Nullable<decimal> NRODESPACHO { get; set; }
        public Nullable<decimal> NROVENTA { get; set; }
        public Nullable<decimal> NROCOBRANZA { get; set; }
        public string CODRETENCION { get; set; }
        public string CODPERCEPCION { get; set; }
        public string CODNEXTEL { get; set; }
        public Nullable<int> MONTFACTURA { get; set; }
        public Nullable<int> MONTBOLETA { get; set; }
        public Nullable<int> MONTNTACREDP { get; set; }
    }
}
