//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEA
    {
        public string CODEMPRESA { get; set; }
        public string CODLINEA { get; set; }
        public string DESLINEA { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<bool> TRANS { get; set; }
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public string CODTIPOPROD { get; set; }
        public decimal CORRELATIVO { get; set; }
    }
}
