//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class rsyssegmentC
    {
        public Nullable<System.DateTime> FECDOCUM { get; set; }
        public string DSTIPODOC { get; set; }
        public string NRODOC { get; set; }
        public string DSTIPOMOV { get; set; }
        public string DESALMACEN { get; set; }
        public string CDARTICULO { get; set; }
        public string DESARTI { get; set; }
        public string CODPRES { get; set; }
        public string despres { get; set; }
        public string CODLINEA { get; set; }
        public string DESLINEA { get; set; }
        public string CODSUBLINEA { get; set; }
        public string DESSUBLINEA { get; set; }
        public string CDPROVEE { get; set; }
        public string DESPROVEEDOR { get; set; }
        public string cdusuario { get; set; }
        public string usuario { get; set; }
        public string ESTADO { get; set; }
        public decimal COSTOBAS { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> CANTXUNI { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
