//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class rsyssegment
    {
        public string RAZONSOCIAL { get; set; }
        public string DSTIPODOC { get; set; }
        public string NRODOCU { get; set; }
        public string CODARTI { get; set; }
        public string DESARTI { get; set; }
        public string CODLINEA { get; set; }
        public string DESLINEA { get; set; }
        public string CODSUBLINEA { get; set; }
        public string DESSUBLINEA { get; set; }
        public string CODPRES { get; set; }
        public string DESPRES { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal IGVBAS { get; set; }
        public decimal SUBTOTBAS { get; set; }
        public System.DateTime FECDOCUM { get; set; }
        public string cdusuario { get; set; }
        public string usuario { get; set; }
        public string NROPTOVTA { get; set; }
        public string ESTADO { get; set; }
        public decimal TOTBAS { get; set; }
    }
}
