//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssegments
    {
        public string CODEMPRESA { get; set; }
        public string codcliente { get; set; }
        public string DATOADJUNTO { get; set; }
        public string Expr1 { get; set; }
        public string DESCRIPCION { get; set; }
        public string DSVEND { get; set; }
        public string Expr2 { get; set; }
    }
}
