//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public Nullable<short> srvid { get; set; }
        public byte[] sid { get; set; }
        public short xstatus { get; set; }
        public System.DateTime xdate1 { get; set; }
        public System.DateTime xdate2 { get; set; }
        public string name { get; set; }
        public byte[] password { get; set; }
        public short dbid { get; set; }
        public string language { get; set; }
        public Nullable<short> isrpcinmap { get; set; }
        public Nullable<short> ishqoutmap { get; set; }
        public Nullable<short> selfoutmap { get; set; }
    }
}
