//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPCREDF
    {
        public string COD_EMPRESA { get; set; }
        public string TIPCREDFAC { get; set; }
        public string DESCREDFAC { get; set; }
        public Nullable<int> NRDIAS { get; set; }
        public Nullable<bool> TRANS { get; set; }
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
