//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPrecioXPromocion
    {
        public string CODEMPRESA { get; set; }
        public string CODPROMO { get; set; }
        public string CODTIPOPRE { get; set; }
        public string DSTIPOPRE { get; set; }
        public string CODIGO { get; set; }
        public int Id { get; set; }
    }
}
