//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPODOC
    {
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public Nullable<bool> TRANS { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<bool> NTACRE { get; set; }
        public string DSABRV { get; set; }
        public string DSTIPODOC { get; set; }
        public string CODTIPODOC { get; set; }
        public string CODEMPRESA { get; set; }
        public bool VTA { get; set; }
        public bool CONTABLE { get; set; }
        public bool COMPRBTECOBRO { get; set; }
        public bool COMPRBTEPAGO { get; set; }
        public Nullable<bool> PERCEP { get; set; }
        public Nullable<bool> PERCEPT { get; set; }
    }
}
