//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_STOCKPEDIDO
    {
        public int CORREL { get; set; }
        public string CODEMPRESA { get; set; }
        public string CODARTI { get; set; }
        public string DESARTI { get; set; }
        public decimal STOCK_PEDIDO_UND { get; set; }
        public decimal STOCK_ACT_UND { get; set; }
        public decimal STOCK_FALT_UND { get; set; }
        public decimal STOCK_FALT_PAQ { get; set; }
        public string CODPRESM { get; set; }
        public string CODPRESU { get; set; }
        public string DESPRESU { get; set; }
        public string DESPRESM { get; set; }
        public string NUM_PEDIDO { get; set; }
        public int Id { get; set; }
    }
}
