//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatafirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_X_COBRAR
    {
        public string CDTIPODOCUM { get; set; }
        public decimal NRODOCU { get; set; }
        public string CDMONEDA { get; set; }
        public string CDCLIENTE { get; set; }
        public decimal TOTCREDBAS { get; set; }
        public decimal TOTCREDEXT { get; set; }
        public System.DateTime FECDOCUM { get; set; }
        public Nullable<decimal> PLAZO { get; set; }
        public System.DateTime VENCIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> PAGCREDBAS { get; set; }
        public Nullable<decimal> PAGCREDEXT { get; set; }
        public string TIPCREDFAC { get; set; }
        public Nullable<bool> TRANS { get; set; }
        public Nullable<System.DateTime> DATETRANS { get; set; }
        public string CODEMPRESA { get; set; }
        public string CDCLIENTEDEP { get; set; }
        public string PTOVTA { get; set; }
        public string DOCUREF { get; set; }
        public Nullable<System.DateTime> fproceso { get; set; }
        public Nullable<bool> PAG { get; set; }
        public string DSCLIENTE { get; set; }
        public string EXISTE { get; set; }
        public Nullable<bool> marca { get; set; }
        public Nullable<decimal> PPAGO { get; set; }
        public string codvend { get; set; }
    }
}
