//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtoReporte
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NARGESTEntities : DbContext
    {
        public NARGESTEntities()
            : base("name=NARGESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_RPT_VENTAS_DETALLE_POR_DOCU_Result> SP_RPT_VENTAS_DETALLE_POR_DOCU(Nullable<int> cODI)
        {
            var cODIParameter = cODI.HasValue ?
                new ObjectParameter("CODI", cODI) :
                new ObjectParameter("CODI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RPT_VENTAS_DETALLE_POR_DOCU_Result>("SP_RPT_VENTAS_DETALLE_POR_DOCU", cODIParameter);
        }
    }
}
