

SELECT * FROM NARGEST.DBO.VENTACAB  WHERE NRODOCU='180003844'


SELECT * FROM dbo.Hoja1$
SELECT CONVERT(INT,SERIE) FROM dbo.Hoja1$

SELECT SUBSTRING ( SERIE ,1 , 2 )+ NUMERO FROM dbo.Hoja1$
GO
SELECT * FROM NARGEST.DBO.VENTACAB WHERE SUBSTRING ( NRODOCU ,1 , 2 ) ='18' AND FECDOCUM='02/04/2013'

   UPDATE NARGEST.DBO.VENTACAB SET FECDOCUM ='01/03/13'
   WHERE NRODOCU = '180099515'
 


HHH

CREATE  PROCEDURE HHH
AS
DECLARE @CODARTI  varchar(255) 
-- Declaración del cursor
DECLARE cClientes CURSOR FOR

SELECT (SUBSTRING ( SERIE ,1 , 2 ) + NUMERO) FROM dbo.Hoja1$

OPEN cClientes
FETCH cClientes INTO @CODARTI
WHILE (@@FETCH_STATUS = 0 )

BEGIN
    -- Lectura de la siguiente fila del cursor
   UPDATE NARGEST.DBO.VENTACAB SET FECDOCUM ='01/04/13'
   WHERE NRODOCU = @CODARTI 
FETCH cClientes INTO  @CODARTI
END

-- Cierre del cursor

CLOSE cClientes

-- Liberar los recursos

DEALLOCATE cClientes