



SELECT SUBSTRING ( NRODOCU ,1 , 3 ), SUBSTRING ( NRODOCU ,4 , 6 ) FROM NARGEST.DBO.VENTACAB  WHERE NRODOCU='120030969'
go
SELECT * FROM NARGEST.DBO.VENTACAB WHERE SUBSTRING ( NRODOCU ,1 , 3 ) ='123' AND NRODOCU='123030969'



DROP TABLE dbo.HOJA2$
SELECT * FROM dbo.HOJA2$
SELECT CONVERT(INT,SERIE) FROM dbo.Hoja1$

SELECT SUBSTRING ( SERIE ,1 , 2 )+ NUMERO FROM dbo.Hoja1$
GO
SELECT * FROM NARGEST.DBO.VENTACAB WHERE SUBSTRING ( NRODOCU ,1 , 3 ) ='123' AND NRODOCU='123030969'
GO
SELECT (SUBSTRING ( SERIE ,1 , 2 ) + NUMERO) FROM dbo.HOJA2$


120030969
HHH
UPDATE NARGEST.DBO.VENTACAB  SET NRODOCU  ='120'+ SUBSTRING ( NRODOCU ,4 , 6 )
WHERE  NRODOCU='123030969'


SELECT * FROM NARGEST.DBO.VENTACAB WHERE NRODOCU  ='120030969'
HHH2

CREATE  PROCEDURE HHH2
AS
DECLARE @CODARTI  varchar(255) 
-- Declaración del cursor
DECLARE cClientes CURSOR FOR

SELECT (SUBSTRING ( SERIE ,1 , 2 ) + NUMERO) FROM dbo.HOJA2$

OPEN cClientes
FETCH cClientes INTO @CODARTI
WHILE (@@FETCH_STATUS = 0 )

BEGIN
    -- Lectura de la siguiente fila del cursor

UPDATE NARGEST.DBO.VENTACAB  SET NRODOCU  ='120'+ SUBSTRING ( @CODARTI ,4 , 6 )
WHERE  NRODOCU=@CODARTI


FETCH cClientes INTO  @CODARTI
END

-- Cierre del cursor

CLOSE cClientes

-- Liberar los recursos

DEALLOCATE cClientes