

SELECT dbo.FN_STOCK_PAQ ('018015','01',186)






CREATE FUNCTION FN_STOCK_PAQ    
(   

@CDART VARCHAR(50),
@CODEMPRESA VARCHAR(50),
@CANT INT
)

RETURNS INT

AS

BEGIN          

DECLARE  @CODPRESMAX UD_CODPRESENTACION                  
DECLARE  @FACTORMAX UD_MONTOS      
DECLARE  @STKACTU INT
Declare @CANTPAQ INT    

SET @CODPRESMAX=(SELECT  TOP 1 CODPRES FROM  ARTIPRESENT  A WHERE A.CODARTI=@CDART AND A.CODEMPRESA=@CODEMPRESA ORDER BY EQUIVALENCIA  DESC )                  
SET @FACTORMAX=(SELECT  TOP 1 EQUIVALENCIA FROM  ARTIPRESENT  A WHERE A.CODARTI=@CDART AND A.CODEMPRESA=@CODEMPRESA ORDER BY EQUIVALENCIA  DESC )                  
         
SET @CANTPAQ=(  @CANT/ @FACTORMAX)  

RETURN @CANTPAQ


END











(SELECT  TOP 1 CODPRES FROM  ARTIPRESENT  A  WHERE A.CODARTI='018015'
 AND A.CODEMPRESA='01' ORDER BY EQUIVALENCIA  asc )    


SELECT  TOP 1 CODPRES,EQUIVALENCIA FROM  ARTIPRESENT  A  WHERE A.CODARTI='018015'AND A.CODEMPRESA='01' ORDER BY EQUIVALENCIA  DESC 





SET @CODPRESMAX=(SELECT  TOP 1 CODPRES FROM  ARTIPRESENT  A WHERE A.CODARTI=@CDART AND A.CODEMPRESA=@CODEMPRESA ORDER BY EQUIVALENCIA  DESC )                  
SET @FACTORMAX=(SELECT  FACTOR   FROM PRESENTACION WHERE  CODPRES=@CODPRESMAX  AND CODEMPRESA=@CODEMPRESA)                  
         
SET @STKACTU=(SELECT  FACTOR * @CANT   FROM PRESENTACION WHERE  CODPRES=@CODPR AND CODEMPRESA=@CODEMPRESA)  