

SP_INSERT_TMP_UTILIDAD

ALTER TABLE TMP_UTILIDAD
ADD FECHA VARCHAR(50)

SP_INSERT_TMP_UTILIDAD '01','02','018'



ALTER PROCEDURE SP_INSERT_TMP_UTILIDAD
@CODEMP VARCHAR(50),
@CODALMACEN VARCHAR(50),
@LINEA VARCHAR(50),
@FECDOCUM1 VARCHAR(50),
@FECDOCUM2 VARCHAR(50)

AS
DELETE FROM TMP_UTILIDAD

INSERT INTO TMP_UTILIDAD(CODEMP, CODARTI, DESARTI, CODALMACEN, DESALMACEN, CODLINEA, CODSUBLINEA, DESLINEA, DESSUBLINEA, CODPRES_V, DESPRES_V, cantidad_V, Cantidad, COSTOBAS_V, COSTOBAS, TOTBAS,FECHA) 

SELECT   DISTINCT  @CODEMP AS CODEMP,MD.CODARTI, MD.DESARTI, MD.CODALMACEN, dbo.ALMACEN.DESALMACEN,                     
                     A.CODLINEA, A.CODSUBLINEA, LINEA.DESLINEA, SUBLINEA.DESSUBLINEA, 
MD.CODPRES AS CODPRES_V,MD.DESPRES AS DESPRES_V ,MD.cantidad AS cantidad_V,DBO.FN_MIN_PRESARTI(@CODEMP,MD.CODARTI,MD.CODPRES,CONVERT(INT,MD.cantidad)) AS Cantidad,
(CONVERT(DECIMAL(9,4),(SELECT ISNULL(COSTOBAS,0) from  FN_RPT_STOCK_ART_ALM_CATE(@CODEMP ) C WHERE C.CODALMACEN IN ( @CODALMACEN) and CODARTI =cast(MD.CODARTI as VARCHAR(100))))) AS COSTOBAS_V,
(CONVERT(DECIMAL(9,4),(SELECT ISNULL(COSTOBAS,0) from  FN_RPT_STOCK_ART_ALM_CATE(@CODEMP ) C WHERE C.CODALMACEN IN ( @CODALMACEN) and CODARTI =cast(MD.CODARTI as VARCHAR(100)))) * CONVERT(INT,(P.factor))) AS COSTOBAS,MD.TOTBAS,
CONVERT(VARCHAR(50),MD.FECDOCUM,103)           

   FROM         ARTICULO A               
INNER JOIN   ARTIDAT ON A.CODARTI = dbo.ARTIDAT.CODARTI AND A.CODEMPRESA= ARTIDAT.CODEMPRESA              
INNER JOIN  ALMACEN ON dbo.ARTIDAT.CODALMACEN = dbo.ALMACEN.CODALMACEN AND A.CODEMPRESA=ALMACEN.CODEMPRESA 
INNER JOIN  LINEA ON A.CODLINEA = dbo.LINEA.CODLINEA AND LINEA.CODEMPRESA=A.CODEMPRESA 
                      INNER join  VENTADET MD ON MD.codarti = A.CODARTI  and convert(char(10),md.fecdocum,103)=dbo.FN_UFECHA_ARTI_2(@CODEMP,dbo.ARTIDAT.CODARTI) 
INNER JOIN  SUBLINEA ON A.CODSUBLINEA = dbo.SUBLINEA.CODSUBLINEA AND  SUBLINEA.CODEMPRESA= A.CODEMPRESA 
                     INNER join ARTIPRESENT AP ON MD.CODARTI=AP.CODARTI AND A.CODEMPRESA=AP.CODEMPRESA 
                     INNER JOIN PRESENTACION P ON  MD.CODPRES=P.CODPRES AND A.CODEMPRESA=P.CODEMPRESA   
  
                 
WHERE     A.CODEMPRESA=@CODEMP   and dbo.ARTIDAT.CODALMACEN =@CODALMACEN AND A.CODLINEA =@LINEA  AND (CONVERT(VARCHAR(50),MD.FECDOCUM,103) BETWEEN  '16/07/2013' AND '17/07/2013')
    
group by  MD.CODARTI,MD.DESARTI, MD.CODALMACEN, dbo.ALMACEN.DESALMACEN,                     
                      A.CODLINEA, A.CODSUBLINEA, LINEA.DESLINEA, SUBLINEA.DESSUBLINEA,                     
                      dbo.ARTIDAT.CODARTI,MD.CODPRES,MD.cantidad,MD.CODPRES,MD.DESPRES,P.factor,MD.TOTBAS,MD.FECDOCUM 



SELECT  * FROM TMP_UTILIDAD WHERE CODARTI='018015'

GO

SELECT  CODEMP, CODARTI, DESARTI, CODALMACEN, DESALMACEN, CODLINEA, CODSUBLINEA, DESLINEA, DESSUBLINEA ,SUM(Cantidad),SUM(COSTOBAS), SUM(TOTBAS) FROM TMP_UTILIDAD WHERE CODARTI='018015'
GROUP BY CODEMP, CODARTI, DESARTI, CODALMACEN, DESALMACEN, CODLINEA, CODSUBLINEA, DESLINEA, DESSUBLINEA


DBO.FN_MIN_PRESARTI('01',A.CODARTI,MD.CODPRES,CONVERT(INT,MD.cantidad)) AS Cantidad 


(CONVERT(DECIMAL(9,4),(SELECT ISNULL(COSTOBAS,0) from  FN_RPT_STOCK_ART_ALM_CATE('01' ) C WHERE C.CODALMACEN IN ( 02) and CODARTI =cast(A.CODARTI as VARCHAR(100)))) ) AS COSTOBAS


* CONVERT(INT,(P.FACTOR))


SELECT FECDOCUM FROM VENTADET VD WHERE VD.NRODOCU='120266766'

SELECT FECDOCUM FROM VENTADET VD WHERE VD.NRODOCU='180111855'



SELECT VD.codarti, FROM VENTADET VD






dbo.FN_MPRESEN_ARTI ('01',A.CODARTI,MD.codpres,convert(numeric(9,3),dbo.FN_UFECHA_ARTI('01',dbo.ARTIDAT.CODARTI)),dbo.FN_UFECHA_ARTI_2('01',dbo.ARTIDAT.CODARTI) ) AS  COSTOBAS






CREATE FUNCTION FN_RPT_STOCK_ART_ALM_CATE2                  
('01' VARCHAR(10)                  
)                  
RETURNS TABLE                  
AS                  
RETURN(        
          
SELECT     '01' AS CODEMP,A.CODARTI, A.DESARTI, ARTIDAT.STKACTU, dbo.ARTIDAT.CODALMACEN, dbo.ALMACEN.DESALMACEN,                     
                     P.DESPRES, A.CODLINEA, A.CODSUBLINEA, LINEA.DESLINEA, ARTIDAT.STKMINM, SUBLINEA.DESSUBLINEA,                     
                      ARTIDAT.ULTING, NULL AS CODPROVEEDOR,NULL AS DESPROV , dbo.FN_MPRESEN_ARTI ('01',A.CODARTI,MD.codpres,convert(numeric(9,3),dbo.FN_UFECHA_ARTI('01',dbo.ARTIDAT.CODARTI)),dbo.FN_UFECHA_ARTI_2('01',dbo.ARTIDAT.CODARTI) ) AS  CO
STOBAS,MD.cantidad        
FROM         ARTICULO A               
INNER JOIN   ARTIDAT ON A.CODARTI = dbo.ARTIDAT.CODARTI AND A.CODEMPRESA= ARTIDAT.CODEMPRESA              
INNER JOIN  ALMACEN ON dbo.ARTIDAT.CODALMACEN = dbo.ALMACEN.CODALMACEN AND A.CODEMPRESA=ALMACEN.CODEMPRESA INNER JOIN                    
                      LINEA ON A.CODLINEA = dbo.LINEA.CODLINEA AND LINEA.CODEMPRESA=A.CODEMPRESA LEFT OUTER JOIN                    
                      SUBLINEA ON A.CODSUBLINEA = dbo.SUBLINEA.CODSUBLINEA AND  SUBLINEA.CODEMPRESA= A.CODEMPRESA INNER JOIN                 
                      ARTIPRESENT AP ON A.CODARTI=AP.CODARTI AND A.CODEMPRESA=AP.CODEMPRESA INNER JOIN                     
                      PRESENTACION P ON AP.CODPRES=P.CODPRES AND A.CODEMPRESA=P.CODEMPRESA                   
                      left join  movidet MD ON MD.cdarticulo = A.CODARTI  and convert(char(10),md.fecdocum,103)=dbo.FN_UFECHA_ARTI_2('01',dbo.ARTIDAT.CODARTI)    AND MD.INOUT=1  and md.cdtipomov='001'  and md.costobas<>0        
WHERE A.FORMU = 0 AND AP.EQUIVALENCIA=1   AND A.CODEMPRESA='01'    
    
group by A.CODARTI, A.DESARTI, ARTIDAT.STKACTU, dbo.ARTIDAT.CODALMACEN, dbo.ALMACEN.DESALMACEN,                     
                     P.DESPRES, A.CODLINEA, A.CODSUBLINEA, LINEA.DESLINEA, ARTIDAT.STKMINM, SUBLINEA.DESSUBLINEA,                     
                      ARTIDAT.ULTING,dbo.ARTIDAT.CODARTI,MD.CODPRES,MD.cantidad      
            
)        
        
      
    
  
