
SELECT * from  FN_RPT_STOCK_ART_ALM_CATE_1('01' ) C WHERE C.CODALMACEN IN ( 02) AND C.CODLINEA IN (018) ORDER BY (CODARTI)


SELECT dbo.FN_STOCK_PAQ (A.CODARTI,'01',ARTIDAT.STKACTU)
SELECT dbo.FN_STOCK_PAQ ('018015','01',186)
ALTER FUNCTION FN_RPT_STOCK_ART_ALM_CATE_1                  
(@CODEMP VARCHAR(10)                  
)                  
RETURNS TABLE                  
AS                  
RETURN(        
          
SELECT    @CODEMP AS CODEMP,A.CODARTI, A.DESARTI, ARTIDAT.STKACTU, dbo.ARTIDAT.CODALMACEN, dbo.ALMACEN.DESALMACEN,                     
                     P.DESPRES, A.CODLINEA, A.CODSUBLINEA, LINEA.DESLINEA, ARTIDAT.STKMINM, SUBLINEA.DESSUBLINEA,                     
                      ARTIDAT.ULTING, NULL AS CODPROVEEDOR,NULL AS DESPROV , dbo.FN_MPRESEN_ARTI (@CODEMP,A.CODARTI,MD.codpres,convert(numeric(9,3),dbo.FN_UFECHA_ARTI(@CODEMP,dbo.ARTIDAT.CODARTI)),dbo.FN_UFECHA_ARTI_2(@CODEMP,dbo.ARTIDAT.CODARTI) ) AS  COSTOBAS,

 dbo.FN_STOCK_PAQ (A.CODARTI,'01',ARTIDAT.STKACTU) AS STK_PAQ
      
FROM         ARTICULO A               
INNER JOIN   ARTIDAT ON A.CODARTI = dbo.ARTIDAT.CODARTI AND A.CODEMPRESA= ARTIDAT.CODEMPRESA              
INNER JOIN  ALMACEN ON dbo.ARTIDAT.CODALMACEN = dbo.ALMACEN.CODALMACEN AND A.CODEMPRESA=ALMACEN.CODEMPRESA INNER JOIN                    
                      LINEA ON A.CODLINEA = dbo.LINEA.CODLINEA AND LINEA.CODEMPRESA=A.CODEMPRESA LEFT OUTER JOIN                    
                      SUBLINEA ON A.CODSUBLINEA = dbo.SUBLINEA.CODSUBLINEA AND  SUBLINEA.CODEMPRESA= A.CODEMPRESA INNER JOIN                 
                      ARTIPRESENT AP ON A.CODARTI=AP.CODARTI AND A.CODEMPRESA=AP.CODEMPRESA INNER JOIN                     
                      PRESENTACION P ON AP.CODPRES=P.CODPRES AND A.CODEMPRESA=P.CODEMPRESA                   
                      left join  movidet MD ON MD.cdarticulo = A.CODARTI  and convert(char(10),md.fecdocum,103)=dbo.FN_UFECHA_ARTI_2(@CODEMP,dbo.ARTIDAT.CODARTI)    AND MD.INOUT=1  and md.cdtipomov='001'  and md.costobas<>0        
WHERE A.FORMU = 0 AND AP.EQUIVALENCIA=1   AND A.CODEMPRESA=@CODEMP    
    
group by A.CODARTI, A.DESARTI, ARTIDAT.STKACTU, dbo.ARTIDAT.CODALMACEN, dbo.ALMACEN.DESALMACEN,                     
                     P.DESPRES, A.CODLINEA, A.CODSUBLINEA, LINEA.DESLINEA, ARTIDAT.STKMINM, SUBLINEA.DESSUBLINEA,                     
                      ARTIDAT.ULTING,dbo.ARTIDAT.CODARTI,MD.CODPRES    
  )        
        
      
    
  
